spring.application.name=literalura

spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect


#aca le estoy dando los perimos para detectar los cambios en la base de datos
spring.jpa.hibernate.ddl-auto=update


#nos permite ver como se comporta la app con la DB
spring.jpa.show-sql=false
spring.jpa.format-sql=false  
